use xyz_company;
CREATE TABLE CUSTOMERS(
ID INT auto_increment PRIMARY KEY ,
NAME VARCHAR(50),
EMAIL VARCHAR(50) UNIQUE,
CITY VARCHAR(50),
JOIN_DATE DATE ,
PHONE CHAR(10) unique
);
DROP TABLE CUSTOMERS;
INSERT INTO CUSTOMERS (ID,NAME,EMAIL,CITY,JOIN_DATE,PHONE) VALUES
(1,"ARYA", "arya@gmail.com","Delhi" , '2023-05-10', 9876543210),
(2,"Riya", "riya@yahoo.com","Mumbai",'2024-02-20',9876543220),
(3,"Priya","priya@gmail.com","Chennai",'2024-06-15',9876543230),
(4,"Aman","aman@hotmail.com","Bangalore",'2023-11-05',9876543240),
(5,"Neha","neha@gmail.com","Delhi",'2024-01-25',9876543250);
SELECT * FROM CUSTOMERS;
CREATE TABLE ORDERS(
ORDER_ID INT auto_increment PRIMARY KEY ,
CUSTOMER_ID INT,
ORDER_DATE date ,
AMOUNT FLOAT,
STATUS VARCHAR(50),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);
DROP TABLE ORDERS;
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, AMOUNT, STATUS) VALUES
(101, 1, '2024-01-10', 1500.50, 'Delivered'),
(102, 2, '2024-02-25', 2500.00, 'Pending'),
(103, 3, '2024-03-05', 3200.75, 'Delivered'),
(104, 1, '2024-04-12', 800.00, 'Delivered'),
(105, 4, '2024-05-18', 1200.00, 'Cancelled'),
(106, 2, '2024-06-20', 4500.25, 'Delivered'),
(107, 5, '2024-07-15', 600.00, 'Pending');
SELECT * FROM ORDERS;
UPDATE CUSTOMERS SET city = 'Bangalore' WHERE ID=3;
delete from ORDERS  where AMOUNT<1000;
SET SQL_SAFE_UPDATES = 0;
SELECT NAME,CITY FROM CUSTOMERS;
SELECT * FROM ORDERS WHERE AMOUNT>2000;
SELECT * FROM CUSTOMERS WHERE JOIN_DATE > 2024-01-01;
SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) AS NUMBER_OF_ORDERS FROM ORDERS GROUP BY CUSTOMER_ID;
SELECT MAX(AMOUNT) AS MAX_AMOUNT , MIN(AMOUNT) AS MIN_AMOUNT , AVG(AMOUNT) AS AVG_AMOUNT FROM ORDERS;
SELECT CUSTOMER_ID , SUM(AMOUNT) AS TOTAL_AMOUNT FROM ORDERS GROUP BY CUSTOMER_ID;
SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) AS NUMBER_OF_ORDERS FROM ORDERS  GROUP BY CUSTOMER_ID HAVING NUMBER_OF_ORDERS > 1 ;
SELECT CUSTOMER_ID , SUM(AMOUNT) AS TOTAL_AMOUNT FROM ORDERS GROUP BY CUSTOMER_ID HAVING TOTAL_AMOUNT > 5000;
SELECT MONTH(ORDER_DATE) AS MONTH_OF_ORDER, COUNT(ORDER_ID) AS NUMBER_OF_ORDERS FROM ORDERS GROUP BY ORDER_DATE ;
SELECT ORDER_ID ,ORDER_DATE FROM ORDERS ORDER BY ORDER_DATE DESC;
SELECT ORDER_ID, AMOUNT FROM ORDERS ORDER BY AMOUNT DESC LIMIT 3;
SELECT ORDER_ID, AMOUNT FROM ORDERS WHERE AMOUNT BETWEEN 1000 AND 5000;
SELECT NAME,CITY FROM CUSTOMERS WHERE CITY ='Delhi' OR CITY= 'Mumbai';
SELECT DISTINCT CITY FROM CUSTOMERS;
SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) AS NUMBER_OF_ORDERS  ,SUM(AMOUNT) AS TOTAL_AMOUNT  FROM ORDERS GROUP BY CUSTOMER_ID HAVING NUMBER_OF_ORDERS > 1 AND TOTAL_AMOUNT>3000 ;
SELECT MONTH(ORDER_DATE) AS MONTH_OF_ORDER, SUM(AMOUNT) AS TOTAL_AMOUNT FROM ORDERS GROUP BY MONTH_OF_ORDER HAVING TOTAL_AMOUNT>5000 ;
SELECT DAY(ORDER_DATE) AS DAY_OF_ORDER, COUNT(ORDER_ID) AS NO_OF_ORDERS FROM ORDERS GROUP BY DAY_OF_ORDER ORDER BY DAY_OF_ORDER ;
SELECT ORDER_ID FROM ORDERS WHERE EMAIL LIKE  '%@gmail.com';
-- SELECT AVG(AMOUNT) AS AVG_AMOUNT FROM ORDERS WHERE AMOUNT!=NULL AND AMOUNT > AVG_AMOUNT  ;
SELECT*FROM ORDERS WHERE AMOUNT > (SELECT AVG(AMOUNT) FROM ORDERS);
START TRANSACTION ;
COMMIT;
UPDATE ORDERS SET AMOUNT = 2600 WHERE ORDER_ID = 102;
UPDATE ORDERS SET AMOUNT = 3300 WHERE ORDER_ID = 103;
COMMIT;
START TRANSACTION;
UPDATE CUSTOMERS SET PHONE = 9512356458 WHERE ID = 3;
SAVEPOINT SP1;

START TRANSACTION;
UPDATE CUSTOMERS SET PHONE = 7563214526 WHERE ID = 1;
SAVEPOINT SP2;
ROLLBACK;

GRANT SELECT,INSERT ON ORDERS TO 'APP_USER';
REVOKE INSERT ON ORDERS FROM 'APP_USER';
GRANT SELECT,INSERT,ALTER,UPDATE,DELETE,TRUNCATE ON CUSTOMERS TO 'ADMIN_USER';
